import { type Metadata } from "next";

import { SidebarClientContainer } from "../../components/sidebar-client-container";

export const metadata: Metadata = {
	title: "Create T3 App",
	description: "Generated by create-t3-app",
	icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default async function RootLayout({
	children,
}: Readonly<{ children: React.ReactNode }>) {
	return (
		<SidebarClientContainer>
			<div className="h-full w-full overflow-y-scroll scroll-smooth rounded-lg bg-[#ffffff] p-11 shadow-md">
				{children}
			</div>
		</SidebarClientContainer>
	);
}
